version: '3.1'

services:
  db:
    image: liupeng0518/mysql:5.7-arm64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql